@baseUrl = http://localhost:5000
@urlPath = api/v1


###
POST {{baseUrl}}/{{urlPath}}/chat/message
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId": "6378e5016e5e9d2e3fb22413",
  "receiverId": "636e6477e7eae7aa28d5e1a8",
  "receiverUsername": "luffy",
  "receiverAvatarColor": "blue",
  "receiverProfilePicture": "",
  "body": "Another msg",
  "gifUrl": "",
  "isRead": false,
  "selectedImage": ""
}


###
POST {{baseUrl}}/{{urlPath}}/chat/message/add-chat-users
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userOne": "6368a5c7d2969c60b9a58f74",
  "userTwo": "636e6477e7eae7aa28d5e1a8"

}

###
GET  {{baseUrl}}/{{urlPath}}/chat/message/conversation-list
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET  {{baseUrl}}/{{urlPath}}/chat/message/user/636e6477e7eae7aa28d5e1a8
Content-Type: application/json
Accept: application/json
withCredentials: true



###
PUT  {{baseUrl}}/{{urlPath}}/chat/message/mark-as-read
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "senderId":"6368a5c7d2969c60b9a58f74",
  "receiverId":"636e6477e7eae7aa28d5e1a8"
}


###
PUT  {{baseUrl}}/{{urlPath}}/chat/message/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "conversationId":"6378e5016e5e9d2e3fb22413",
  "messageId":"6378e5016e5e9d2e3fb22412",
  "reaction": "angry" ,
  "type":"remove"
}




###
DELETE  {{baseUrl}}/{{urlPath}}/chat/message/mark-as-deleted/6379bc22dbd86e891b67d446/6368a5c7d2969c60b9a58f74/636e6477e7eae7aa28d5e1a8/deleteForEveryone
Accept: application/json
withCredentials: true

