@baseUrl = http://localhost:5000
@urlPath = api/v1


###
GET {{baseUrl}}/{{urlPath}}/user/following
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/user/followers/6368a5c7d2969c60b9a58f74
Content-Type: application/json
Accept: application/json
withCredentials: true

###Follow a user
PUT {{baseUrl}}/{{urlPath}}/user/follow/6378e7916e5e9d2e3fb2241b
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###Unfollow a user PUT {{baseUrl}}/{{urlPath}}/user/unfollow/<OtherUser>/<loggedInuserId>
PUT {{baseUrl}}/{{urlPath}}/user/unfollow/6368a5c7d2969c60b9a58f74/636e6477e7eae7aa28d5e1a8
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###BLOCK A USER
PUT {{baseUrl}}/{{urlPath}}/user/block/6368a5c7d2969c60b9a58f74
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###UNBLOCK A USER
PUT {{baseUrl}}/{{urlPath}}/user/unblock/6368a5c7d2969c60b9a58f74
Content-Type: application/json
Accept: application/json
withCredentials: true

{}