@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true

###UPDATE NOTIFication
PUT {{baseUrl}}/{{urlPath}}/notification/63709d0eb6259c3de4864460
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
DELETE {{baseUrl}}/{{urlPath}}/notification/63709d700365f4d2cb1dfee7
Content-Type: application/json
Accept: application/json
withCredentials: true

{}