@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "5th  Post",
  "bgColor": "white",
  "privacy": "pubic",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png",
  "feelings": "sad"
}

###
POST {{baseUrl}}/{{urlPath}}/post/image/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "3rd Post with img",
  "bgColor": "green",
  "privacy": "pubic",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png",
  "feelings": "sad",
  "image":"https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png"

}

###GET ALL POSTS FROM CACHE/DB
GET  {{baseUrl}}/{{urlPath}}/post/all/1 
Content-Type: application/json
Accept: application/json
withCredentials: true

###GET  POSTS WITH IMAGES/GIF FROM CACHE/DB
GET  {{baseUrl}}/{{urlPath}}/post/images/2
Content-Type: application/json
Accept: application/json
withCredentials: true


###DELETE POST GIVEN POSTID
DELETE {{baseUrl}}/{{urlPath}}/post/6368a5f8d2969c60b9a58f79
Content-Type: application/json
Accept: application/json
withCredentials: true

###UPDATE POST GIVEN POSTID
PUT {{baseUrl}}/{{urlPath}}/post/6368a7a1d2969c60b9a58f89
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "post": "MY good Updated Post",
  "bgColor": "Yellow",
  "privacy": "private",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png",
  "feelings": "wow",
  "imgId":"",
  "imgVersion":""
}

###
PUT {{baseUrl}}/{{urlPath}}/post/image/6368a654d2969c60b9a58f7d
Content-Type: application/json
Accept: application/json
withCredentials: true,

{
  "post": "Good Updated Post 2",
  "bgColor": "Yellow",
  "privacy": "private",
  "gifUrl": "",
  "profilePicture": "https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png",
  "feelings": "wow",
  "imgId":"egl900bm9wn9sn4p4fqo",
  "imgVersion":"1667802712",
  "image":"https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png"
}




