@baseUrl = http://localhost:5000
@urlPath = api/v1

###ADD REACTIONS
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

# type - like | love | wow | happy | sad | angry
# previousReaction (if it exist) - like | love | wow | happy | sad | angry
# postReactions - increment new reaction by 1 and decrement previous reaction by 1

{
  "userTo": "6368a5c7d2969c60b9a58f74",
  "postId": "6368a786d2969c60b9a58f81",
  "type": "wow",
  "previousReaction": "",
  "postReactions": {"like": 0 ,"love": 0,"happy": 0,"sad": 0,"wow": 1,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/dnslnpn4l/image/upload/v1667630010/636603b7660fd48a850d800f.png"
}



###REMOVE REACTIONS
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/6368a654d2969c60b9a58f7d/love/{"like": 0 ,"love": 0,"happy": 0,"sad": 0,"wow": 0,"angry": 0}
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###Get all REACTIONS for a post
GET  {{baseUrl}}/{{urlPath}}/post/reactions/638042ef3a62550b4e3a5210
Accept: application/json
withCredentials: true



###Get single REACTION for a post given username
GET  {{baseUrl}}/{{urlPath}}/post/single/reaction/username/Izuku/6368a786d2969c60b9a58f81
Accept: application/json
withCredentials: true



###Get all REACTION for a given username
GET  {{baseUrl}}/{{urlPath}}/post/reactions/username/Asta
Accept: application/json
withCredentials: true
