@baseUrl = http://localhost:5000
@urlPath = api/v1

###
GET {{baseUrl}}/{{urlPath}}/user/all/1
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/user/profile
Content-Type: application/json
Accept: application/json
withCredentials: true



###
GET {{baseUrl}}/{{urlPath}}/user/profile/6368a5c7d2969c60b9a58f74
Content-Type: application/json
Accept: application/json
withCredentials: true



###
GET {{baseUrl}}/{{urlPath}}/user/profile/posts/asta/6368a5c7d2969c60b9a58f74/94423597859
Content-Type: application/json
Accept: application/json
withCredentials: true

###get random users
GET {{baseUrl}}/{{urlPath}}/user/profile/user/suggestions
Content-Type: application/json
Accept: application/json
withCredentials: true


###search users
GET {{baseUrl}}/{{urlPath}}/user/profile/search/izu
Content-Type: application/json
Accept: application/json
withCredentials: true

###search users
PUT  {{baseUrl}}/{{urlPath}}/user/profile/change-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
   "currentPassword":"password",
   "newPassword": "newpassword",
   "confirmPassword":"newpassword"
}


###
PUT {{baseUrl}}/{{urlPath}}/user/profile/basic-info
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "quote": "Today is a gift",
  "work": "",
  "school": "paul",
  "location": "Mumbai,India"
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/social-links
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "instagram": "",
  "twitter": "",
  "facebook": "facebokk/fake",
  "youtube": ""
}

###
PUT {{baseUrl}}/{{urlPath}}/user/profile/settings
content-type: application/json
Accept: 'application/json'
withCredentials: true

{
  "messages": false,
  "reactions": true,
  "comments": false,
  "follows": true
}





